enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

start-at-login = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[mode.main.binding]
    alt-h =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-j =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-l =         'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-k = 'move down'
    alt-shift-j = 'move up'
    alt-shift-l = 'move right'


    alt-s = 'fullscreen'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'

    alt-r = 'mode resize'

    alt-f = 'workspace next'
    alt-a = 'workspace prev'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    0 = 'balance-sizes'
    r = ['flatten-workspace-tree', 'mode main']
   enter = 'mode main'
    esc = 'mode main'
